---
title: "Meta data analysis"
author: "Florian Pätzold"
date: "2023-09-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

Import all necessary packages.

```{r}
library(dplyr)
```

# Data pre-processing

```{r}
# Set working directory to folder with localization files
setwd("/Users/florian/Documents/Studium/NBP/Projects/OptiVisT/FloBox/Experiment/Data/Meta/")
# Read csv data
meta_data <- read.csv("meta.csv")

# Clean data
# remove pilot trials and last row
meta_data <- tail(meta_data, n = -4)
meta_data <- head(meta_data, n = -1)

# rename cols
meta_data <- meta_data %>% rename(participant_id = Participant.., 
                                  sex = Sex, 
                                  age = Age, 
                                  condition_order = Condition.Order, 
                                  experimenter = Experimenter, 
                                  assistant = Assistant.Experimenter,
                                  bracelet = Bracelet,
                                  handedness = Handedness,
                                  previous_experience = Ramon.s.Study.,
                                  date = Date.of.Session,
                                  start = Start.Time.of.Session,
                                  end = End.Time.of.Session,
                                  localization_attempts = X..of.Localization.Blocks..1.3.,
                                  localization_acc = Final.Localization.Accuracy,
                                  notes = Notes,
                                  cleaning = Manual.data.cleaning)

# remove notes in cols for P7
meta_data$localization_attempts[7] <- "1"
meta_data$localization_acc[7] <- "100"

# remove notes (including manual data cleaning notes)
meta_data <- meta_data %>% select(-c(notes, cleaning)) %>% mutate(
    participant_id = as.integer(participant_id),
    age = as.integer(age),
    #sex = as.integer(ifelse(sex == 'f', 1, 0)), # binary
    #experimenter = as.integer(ifelse(experimenter == 'Piper', 0, ifelse(experimenter == 'Milad', 1, 2))), # tertiary
    localization_acc = as.numeric(localization_acc)
  )

# cleaned data
meta_data
```

# Analysis

```{r}
# sex
meta_data %>% group_by(sex) %>% summarize(count = n())

# age
mean(meta_data$age, na.rm=TRUE)
sd(meta_data$age, na.rm=TRUE)

# handedness
meta_data %>% group_by(handedness) %>% summarize(count = n())

# Ramon's study?
meta_data %>% group_by(previous_experience) %>% summarize(count = n())

# summary accuracy statistics per attempts
meta_data %>% group_by(localization_attempts) %>% summarize(mean = mean(localization_acc), sd = sd(localization_acc), count = n())
```

